/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class no5_lane8_liangzhou_homework2_MyTest */

#ifndef _Included_no5_lane8_liangzhou_homework2_MyTest
#define _Included_no5_lane8_liangzhou_homework2_MyTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     no5_lane8_liangzhou_homework2_MyTest
 * Method:    getString
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_no5_lane8_liangzhou_homework2_MyTest_getString
  (JNIEnv *env, jobject obj){

  jclass cla=env->GetObjectClass(obj);
  jfieldID id_test_str=env->GetFieldID(cla,"number","I");
  env->SetIntField(obj,id_test_str,10);
}

#ifdef __cplusplus
}
#endif
#endif
