/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class no5_lane8_liangzhou_homework2_MyTest */

#ifndef _Included_no5_lane8_liangzhou_homework2_MyTest
#define _Included_no5_lane8_liangzhou_homework2_MyTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     no5_lane8_liangzhou_homework2_MyTest
 * Method:    getString
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_no5_lane8_liangzhou_homework2_MyTest_getString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
